CREATE TABLE TB_AESTHETICS
(
NOME VARCHAR2(30),
NOME_AESTHETIC VARCHAR2(50),
IDADE INTEGER,
SEXO VARCHAR2(1)

)


INSERT INTO TB_AESTHETICS
(NOME, NOME_AESTHETIC, IDADE, SEXO)
VALUES
('Azizz', 'Zyzz', '22', 'm')

INSERT INTO TB_AESTHETICS
(NOME, NOME_AESTHETIC, IDADE, SEXO)
VALUES
('Jeff', 'Jeff Seid', '29', 'm')

INSERT INTO TB_AESTHETICS
(NOME, NOME_AESTHETIC, IDADE, SEXO)
VALUES
('David', 'Laid', '25', 'm')

drop table TB_AESTHETICS